In [148]:
import pandas as pd
A =pd.read_csv("/content/AirbnbAnalysis.csv")

In [16]:
A.shape

(5555, 38)

In [194]:
A.dtypes

_id                              int64
name                            object
property_type                   object
room_type                       object
bed_type                        object
minimum_nights                   int64
maximum_nights                   int64
cancellation_policy             object
first_review                    object
last_review                     object
accommodates                     int64
bedrooms                         int64
beds                             int64
number_of_reviews                int64
bathrooms                        int64
amenities                       object
price                            int64
security_deposit               float64
extra_people                     int64
guests_included                  int64
address_street                  object
country                         object
host_neighbourhood              object
host_name                       object
host_response_rate               int64
review_scores_accuracy           int64
review_scores_cleanliness        int64
review_scores_checkin            int64
review_scores_communication      int64
review_scores_location           int64
review_scores_value              int64
review_scores_rating             int64
availability_30                  int64
availability_60                  int64
availability_90                  int64
availability_365                 int64
weekly_price                   float64
monthly_price                  float64
dtype: object

In [198]:

A.reset_index(inplace=True)

In [199]:
A

,index,_id,name,property_type,room_type,bed_type,minimum_nights,maximum_nights,cancellation_policy,first_review,...,review_scores_communication,review_scores_location,review_scores_value,review_scores_rating,availability_30,availability_60,availability_90,availability_365,weekly_price,monthly_price
0,0,10006546,Ribeira Charming Duplex,House,Entire home/apt,Real Bed,2,30,moderate,2016-01-03 05:00:00,...,10,10,9,89,28,47,74,239,NaN,NaN
1,2,1001265,Ocean View Waikiki Marina w/prkg,Condominium,Entire home/apt,Real Bed,3,365,strict_14_with_grace_period,2013-05-24 04:00:00,...,9,10,9,84,16,46,76,343,650.0,2150.0
2,3,10021707,Private Room in Bushwick,Apartment,Private room,Real Bed,14,1125,flexible,2016-01-31 05:00:00,...,10,8,8,100,0,0,0,0,NaN,NaN
3,5,1003530,New York City - Upper West Side Apt,Apartment,Private room,Real Bed,12,360,strict_14_with_grace_period,2013-04-29 04:00:00,...,10,10,10,94,0,0,0,93,NaN,NaN
4,6,10038496,Copacabana Apartment Posto 6,Apartment,Entire home/apt,Real Bed,3,75,strict_14_with_grace_period,2016-01-18 05:00:00,...,10,10,10,98,7,19,33,118,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4064,5549,9981541,Economy 2-beds room (308),Apartment,Private room,Real Bed,1,1125,strict_14_with_grace_period,2015-12-19 05:00:00,...,10,8,7,80,30,60,90,365,NaN,NaN
4065,5550,9983221,Cozy apartment downtown Porto,Apartment,Entire home/apt,Real Bed,3,1125,strict_14_with_grace_period,2016-01-03 05:00:00,...,10,10,10,98,26,51,77,300,NaN,NaN
4066,5552,9987200,The best suite in Copacabana (total privacy),Aparthotel,Private room,Real Bed,3,60,flexible,2016-01-06 05:00:00,...,10,10,9,97,7,29,53,53,NaN,NaN
4067,5553,9990304,March Madness Special! Aina Nalu Platinum D107,Condominium,Entire home/apt,Real Bed,3,365,strict_14_with_grace_period,2015-08-17 04:00:00,...,10,10,9,97,8,20,26,243,NaN,NaN
4068,5554,9993190,Just Steps from the Ocean at Premier Platinum ...,Townhouse,Entire home/apt,Real Bed,3,365,strict_14_with_grace_period,2016-04-06 04:00:00,...,10,10,9,92,0,8,31,258,NaN,NaN

In [203]:
A["price"] = A["price"].astype('int')

In [195]:
A["first_review"]

0       2016-01-03 05:00:00
2       2013-05-24 04:00:00
3       2016-01-31 05:00:00
5       2013-04-29 04:00:00
6       2016-01-18 05:00:00
               ...
5549    2015-12-19 05:00:00
5550    2016-01-03 05:00:00
5552    2016-01-06 05:00:00
5553    2015-08-17 04:00:00
5554    2016-04-06 04:00:00
Name: first_review, Length: 4069, dtype: object

In [31]:
A["last_review"] = A["last_review"].fillna(0)
A["first_review"] = A["first_review"].fillna(0)

In [72]:
V = A[A["bathrooms"]==0]
print(V[["beds","bedrooms","bathrooms"]])

      beds  bedrooms  bathrooms
397    2.0       1.0        0.0
407    1.0       1.0        0.0
712    2.0       1.0        0.0
1864   2.0       0.0        0.0
3395   1.0       0.0        0.0
3476   1.0       1.0        0.0
3666   1.0       1.0        0.0
3681   NaN       0.0        0.0
3701   2.0       1.0        0.0
3959   1.0       1.0        0.0
4849   1.0       1.0        0.0
4992   2.0       2.0        0.0
5465   2.0       1.0        0.0
5486   1.0       1.0        0.0

In [80]:
A[A["review_scores_location"]==0]
A[["review_scores_location","review_scores_cleanliness"]]

      review_scores_location  review_scores_cleanliness
0                       10.0                        9.0
1                        NaN                        NaN
2                       10.0                        8.0
3                        8.0                       10.0
4                        NaN                        NaN
...                      ...                        ...
5550                    10.0                       10.0
5551                     NaN                        NaN
5552                    10.0                       10.0
5553                    10.0                       10.0
5554                    10.0                        9.0

[5555 rows x 2 columns]

In [74]:
print(A[["weekly_price","price"]].head(30))

    weekly_price  price
0            NaN   80.0
1         1492.0  317.0
2          650.0  115.0
3            NaN   40.0
4            NaN  701.0
5            NaN  135.0
6            NaN  119.0
7            NaN  527.0
8            NaN  250.0
9            NaN   50.0
10           NaN  205.0
11           NaN   43.0
12        5000.0  699.0
13           NaN  140.0
14           NaN  858.0
15           NaN  361.0
16           NaN   50.0
17           NaN   30.0
18        1350.0  181.0
19           NaN  181.0
20         387.0   58.0
21        1000.0  145.0
22           NaN  185.0
23           NaN  250.0
24         230.0   40.0
25           NaN  838.0
26           NaN  997.0
27           NaN  933.0
28           NaN   40.0
29           NaN  150.0

In [165]:
A.isna().sum()

_id                               0
name                              1
property_type                     0
room_type                         0
bed_type                          0
minimum_nights                    0
maximum_nights                    0
cancellation_policy               0
first_review                      0
last_review                       0
accommodates                      0
bedrooms                          0
beds                              0
number_of_reviews                 0
bathrooms                         0
amenities                         0
price                             0
security_deposit               1217
extra_people                      0
guests_included                   0
address_street                    0
country                           0
host_neighbourhood             1224
host_name                         0
host_response_rate                0
review_scores_accuracy            0
review_scores_cleanliness         0
review_scores_checkin             0
review_scores_communication       0
review_scores_location            0
review_scores_value               0
review_scores_rating              0
availability_30                   0
availability_60                   0
availability_90                   0
availability_365                  0
weekly_price                   3463
monthly_price                  3512
dtype: int64

In [ ]:
A["host_response_rate"]

In [160]:
A.dropna(subset=["bathrooms"], inplace=True)

In [164]:
A["host_response_rate"].fillna(100,inplace = True)

In [167]:
A.drop_duplicates(inplace = True)

In [ ]:
import matplotlib.pyplot as plt
A.plot(x='beds', y='bedrooms', kind='scatter')
plt.show()

In [111]:
# Assuming 'A' is your DataFrame
A.drop_duplicates(inplace=True)

In [106]:
# Assuming 'A' is your DataFrame
A.drop_duplicates(subset=['host_name'], inplace=True)